/**
 * @file main.c
 * @brief STM32F446RE main entry point – FreeRTOS scheduler with control tasks
 */

#include "stm32f4xx_hal.h"
#include "FreeRTOS.h"
#include "task.h"

/* Application headers */
#include "thermal_control.h"
#include "motion_control.h"
#include "pump_control.h"
#include "safety.h"
#include "hmi_logger.h"

/* ==================== HAL Forward Declarations ======================== */

extern void SystemClock_Config(void);
extern void MX_GPIO_Init(void);
extern void MX_SPI1_Init(void);
extern void MX_USART2_UART_Init(void);
extern void MX_TIM1_Init(void);
extern void MX_TIM2_Init(void);
extern void MX_TIM4_Init(void);

/* ==================== Global Variables ================================ */

static TaskHandle_t xTaskHandle_Safety;
static TaskHandle_t xTaskHandle_ThermalCtrl;
static TaskHandle_t xTaskHandle_MotionCtrl;
static TaskHandle_t xTaskHandle_PumpCtrl;
static TaskHandle_t xTaskHandle_HMI;

/* ==================== FreeRTOS Hooks ================================= */

/**
 * @brief Called when a task stack overflows
 */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {
    (void) xTask;
    (void) pcTaskName;
    /* Halt the system */
    __disable_irq();
    for (;;);
}

/**
 * @brief Called when malloc() fails
 */
void vApplicationMallocFailedHook(void) {
    /* Halt the system */
    __disable_irq();
    for (;;);
}

/* ==================== System Initialization =========================== */

/**
 * @brief Initialize all HAL peripherals
 */
static void HAL_Init_All(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_SPI1_Init();          /* MAX31865 (thermal) */
    MX_USART2_UART_Init();   /* Debug console */
    MX_TIM1_Init();          /* SSR PWM (10 Hz) */
    MX_TIM2_Init();          /* STEP pulse generation */
    MX_TIM4_Init();          /* Pump PWM (10 Hz) */
}

/**
 * @brief Initialize all application subsystems
 */
static void App_Init_All(void) {
    Safety_Init();          /* Safety (1 kHz) */
    Thermal_Init();         /* Thermal control (25 Hz) */
    Motion_Init();          /* Motion control (timer-driven) */
    Pump_Init();            /* Pump control (10 Hz) */
    HMI_Init();             /* HMI/Logger (1 Hz) */
}

/**
 * @brief Create all FreeRTOS tasks
 */
static void Tasks_Create(void) {
    /* Safety task: Highest priority (1 kHz) */
    xTaskCreate(
        Safety_MonitorTask,
        "Safety",
        512,
        NULL,
        5,  /* High priority */
        &xTaskHandle_Safety
    );

    /* Thermal task: High priority (25 Hz), controls SSR (10 Hz internal) */
    xTaskCreate(
        Thermal_ControlTask,
        "ThermalCtrl",
        512,
        NULL,
        4,
        &xTaskHandle_ThermalCtrl
    );

    /* Motion task: Medium-high priority (timer-driven STEP at ~1 kHz) */
    xTaskCreate(
        Motion_ControlTask,
        "MotionCtrl",
        512,
        NULL,
        3,
        &xTaskHandle_MotionCtrl
    );

    /* Pump task: Medium priority (10 Hz PWM) */
    xTaskCreate(
        Pump_ControlTask,
        "PumpCtrl",
        512,
        NULL,
        2,
        &xTaskHandle_PumpCtrl
    );

    /* HMI task: Lower priority (1 Hz logging) */
    xTaskCreate(
        HMI_Task,
        "HMI",
        512,
        NULL,
        1,  /* Low priority */
        &xTaskHandle_HMI
    );
}

/* ==================== main() ========================================== */

/**
 * @brief Application entry point
 */
int main(void) {
    /* Initialize HAL & peripherals */
    HAL_Init_All();
    
    /* Initialize application subsystems */
    App_Init_All();
    
    /* Create FreeRTOS tasks */
    Tasks_Create();
    
    /* Start FreeRTOS scheduler (never returns) */
    vTaskStartScheduler();
    
    /* Should never reach here */
    for (;;) {
        __NOP();
    }
    
    return 0;
}

/* ==================== System Callbacks ================================ */

/**
 * @brief SysTick interrupt handler (FreeRTOS tick)
 */
void SysTick_Handler(void) {
    HAL_IncTick();
    if (xTaskGetSchedulerState() != taskSCHEDULER_NOT_STARTED) {
        xPortSysTickHandler();
    }
}

/**
 * @brief TIM2 Update interrupt (stepper STEP pulse counting)
 */
void TIM2_IRQHandler(void) {
    if (__HAL_TIM_GET_FLAG(&htim2, TIM_FLAG_UPDATE)) {
        __HAL_TIM_CLEAR_FLAG(&htim2, TIM_FLAG_UPDATE);
        Motion_StepInterrupt();
    }
}

/* Note: Additional interrupt handlers (SPI, USART, etc.) 
   are generated by STM32CubeMX and should be placed in stm32f4xx_it.c */

#endif /* main */
